version: '2.3'

services:

  nginx:
    build: ./webapp/
    image: dannixon/hebi-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "8080:80"

  api:
    build: ./webservice/
    image: dannixon/hebi-api
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # Set to something sensible for you
      - "/media/data/testing/:/data"

  dataserver:
    image: dannixon/dawn-dataserver:latest
    volumes:
      # Set to something sensible for you
      - "/media/data/testing/:/data"
