CONFIG_NAMESPACE_SAVU = 'SAVU'
CONFIG_KEY_JOB_RUNNERS = 'job_runners'
CONFIG_KEY_RUNNER_INSTANCE = 'instance'
CONFIG_KEY_RUNNER_MODULE = 'module'
CONFIG_KEY_RUNNER_CLASS = 'class'
CONFIG_KEY_RUNNER_PARAMETERS = 'parameters'

WS_NAMESPACE_JOB_STATUS = '/job_status'

EVENT_JOB_STATUS = 'status'

KEY_JOB_ID = 'job'
KEY_QUEUE_ID = 'queue'
