apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: PGID
          value: "1205104"
        - name: PUID
          value: "1205104"
        image: dannixon/hebi-api
        name: api
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: vol-data
      restartPolicy: Always
      volumes:
      - name: vol-data
        persistentVolumeClaim:
          claimName: dlstmp
status: {}
