apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dataserver
  name: dataserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dataserver
    spec:
      containers:
      - image: dannixon/dawn-dataserver:latest
        name: dataserver
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: vol-data
      restartPolicy: Always
      volumes:
      - name: vol-data
        persistentVolumeClaim:
          claimName: dlstmp
status: {}
